"""
app/models/verification_test.py — Skill verification test (optional / stretch).

Implements IDEA.md §3 VerificationTest. Used in Phase 8 if built.
Included in Phase 1 so the full schema exists from the start.

Flow (Phase 8):
  1. Employer requests a test for employee+skill.
  2. Claude generates a short question set → stored in generated_prompt.
  3. Employer records the employee's score manually.
  4. Rating update runs with source = "verification_test".
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.employee import Employee
    from app.models.skill import Skill


class VerificationTest(Base):
    __tablename__ = "verification_tests"

    id: Mapped[int] = mapped_column(primary_key=True)
    employee_id: Mapped[int] = mapped_column(
        ForeignKey("employees.id", ondelete="CASCADE"), nullable=False, index=True
    )
    skill_id: Mapped[int] = mapped_column(
        ForeignKey("skills.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    # The prompt / question set generated by Claude
    generated_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    # Score recorded by employer after observing the employee's answers (nullable until scored)
    employer_recorded_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    # True once the score has been fed into the rating update
    applied: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    employee: Mapped[Employee] = relationship(
        "Employee", back_populates="verification_tests"
    )
    skill: Mapped[Skill] = relationship(
        "Skill", back_populates="verification_tests"
    )

    def __repr__(self) -> str:
        return (
            f"<VerificationTest id={self.id} "
            f"employee_id={self.employee_id} skill_id={self.skill_id} "
            f"applied={self.applied}>"
        )
